const tagList = [
  'Single-player',
  'Multi-player', 
  'Cross-Platform Multiplayer',
  'Steam Achievements',
  'Mundo Abierto',
  'Multijugador',
  'Coperativo',
  'Juegos Online',
  'Contenido Sexual',
  '2D',
  'Competitivo',
  'Customizacion de Personajes',
  'Protagonista Mujer',
  'Díficil',
  'Diseño e ilustración',
  'Deportes',
  'Multijugador',
  'Aventura',
  'Shooter en primera Persona',
  'Shooter',
  'Shooter en tercera Persona',
  'Francotiradores',
  'Tercera Persona',
  'Carreras',
  'Acceso Anticipado',
  'Supervivencia',
  'Graficos Pixeleados',
  'Adorable',
  'Fisicas',
  'Ciencia',
  'VR',
  'Tutorial',
  'Clásico',
  'Gore',
  "1990's",
  'Un solo jugador',
  'Ciencia Ficción',
  'Aliens',
  'Primera Persona',
  'Horror Psicológico',
  'Sandbox',
  'Mod',
  'Animación y Modelado',
  'Rompecabezas',
  'Horror',
  'Futurístico',
  'Ciberpunk',
  'Destrucción',
  'Música',
  'Conduciendo',
  'Arcano',
  'Mecas',
  'Robots',
  'Subterraneo',
  'Exploración'
]

export default tagList